Provision task execution role (#8)
DataBiosphere/cellxgene-fargate pull request #10
Opened 2020-04-03 08:03 UTC by danielsotirhos

2020-04-06 21:30 UTC, nadove-ucsc approved these changes

2020-04-07 18:12 UTC, hannes-ucsc requested changes

2020-04-07 18:12 UTC, hannes-ucsc commented on terraform/cellxgene.tf.json.template.py
> +                "assume_role_policy": "${data.aws_iam_policy_document.ecs-task-assume-role.json}"
Assume role policies (and other policies that are referenced exactly once) I prefer not to go though the `data` indirection.

https://github.com/DataBiosphere/azul/blob/0964b1c2c4eff3d91b0b21b63af183793c15cb80/terraform/gitlab/gitlab.tf.json.template.py#L837

2020-04-07 18:12 UTC, hannes-ucsc commented on terraform/cellxgene.tf.json.template.py
> +                "arn": "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
It does not make sense to look up an `aws_iam_policy` data source by ARN if that ARN is well-known and documented and …

2020-04-07 18:12 UTC, hannes-ucsc commented on terraform/cellxgene.tf.json.template.py
> +                "policy_arn": "${data.aws_iam_policy.ecs-task-execution-role-policy.arn}"
… the only thing you need from that data source is the ARN.

2020-04-13 17:43 UTC, merged